import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { Oswald } from 'next/font/google';
import "./globals.css";
import { ToastContainer } from "react-toastify";
import Navbar from "@/components/shared/Navbar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });


// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const oswald = Oswald({
  subsets: ['latin'],
  weight: ['400', '700'], // Specify the weights you need
  display: 'swap',        // Recommended for performance
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${oswald.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
      
      <Navbar />
      {children}

      <ToastContainer />
      
      </body>
    </html>
  );
}
